"""Veriificacao

Revision ID: 948604d795d9
Revises: 
Create Date: 2022-12-03 17:08:47.471805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948604d795d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
